
#line 3 "nds32-aie-scanner.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer nds32_aie_scanner__create_buffer
#define yy_delete_buffer nds32_aie_scanner__delete_buffer
#define yy_flex_debug nds32_aie_scanner__flex_debug
#define yy_init_buffer nds32_aie_scanner__init_buffer
#define yy_flush_buffer nds32_aie_scanner__flush_buffer
#define yy_load_buffer_state nds32_aie_scanner__load_buffer_state
#define yy_switch_to_buffer nds32_aie_scanner__switch_to_buffer
#define yyin nds32_aie_scanner_in
#define yyleng nds32_aie_scanner_leng
#define yylex nds32_aie_scanner_lex
#define yylineno nds32_aie_scanner_lineno
#define yyout nds32_aie_scanner_out
#define yyrestart nds32_aie_scanner_restart
#define yytext nds32_aie_scanner_text
#define yywrap nds32_aie_scanner_wrap
#define yyalloc nds32_aie_scanner_alloc
#define yyrealloc nds32_aie_scanner_realloc
#define yyfree nds32_aie_scanner_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE nds32_aie_scanner_restart(nds32_aie_scanner_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int nds32_aie_scanner_leng;

extern FILE *nds32_aie_scanner_in, *nds32_aie_scanner_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up nds32_aie_scanner_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up nds32_aie_scanner_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via nds32_aie_scanner_restart()), so that the user can continue scanning by
	 * just pointing nds32_aie_scanner_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when nds32_aie_scanner_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int nds32_aie_scanner_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow nds32_aie_scanner_wrap()'s to do buffer switches
 * instead of setting up a fresh nds32_aie_scanner_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void nds32_aie_scanner_restart (FILE *input_file  );
void nds32_aie_scanner__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE nds32_aie_scanner__create_buffer (FILE *file,int size  );
void nds32_aie_scanner__delete_buffer (YY_BUFFER_STATE b  );
void nds32_aie_scanner__flush_buffer (YY_BUFFER_STATE b  );
void nds32_aie_scanner_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void nds32_aie_scanner_pop_buffer_state (void );

static void nds32_aie_scanner_ensure_buffer_stack (void );
static void nds32_aie_scanner__load_buffer_state (void );
static void nds32_aie_scanner__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER nds32_aie_scanner__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE nds32_aie_scanner__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE nds32_aie_scanner__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE nds32_aie_scanner__scan_bytes (yyconst char *bytes,int len  );

void *nds32_aie_scanner_alloc (yy_size_t  );
void *nds32_aie_scanner_realloc (void *,yy_size_t  );
void nds32_aie_scanner_free (void *  );

#define yy_new_buffer nds32_aie_scanner__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        nds32_aie_scanner_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            nds32_aie_scanner__create_buffer(nds32_aie_scanner_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        nds32_aie_scanner_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            nds32_aie_scanner__create_buffer(nds32_aie_scanner_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define nds32_aie_scanner_wrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *nds32_aie_scanner_in = (FILE *) 0, *nds32_aie_scanner_out = (FILE *) 0;

typedef int yy_state_type;

extern int nds32_aie_scanner_lineno;

int nds32_aie_scanner_lineno = 1;

extern char *nds32_aie_scanner_text;
#define yytext_ptr nds32_aie_scanner_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up nds32_aie_scanner_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	nds32_aie_scanner_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 107
#define YY_END_OF_BUFFER 108
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[273] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,  108,  106,
        1,  105,   24,   93,   22,   21,    3,   25,   31,   15,
       16,    9,    8,    4,    7,   11,   10,  104,    6,    5,
       13,   12,   14,   27,  104,  104,  104,  104,   17,   18,
       28,   30,  104,   92,  104,  104,  104,  104,  104,  104,
      104,   91,  104,  104,  104,   19,   26,   20,   29,   99,
       98,  103,  102,  103,   95,   96,   94,    0,   23,  100,
       97,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,   86,   83,   85,  104,  104,   84,  104,  104,

       90,   87,   89,   88,  104,  104,  101,    0,  104,  104,
      104,   81,   79,  104,  104,   82,   80,  104,  104,   48,
       49,  104,  104,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,  104,  104,
        0,   57,   58,   59,   60,   75,   77,   76,   78,  104,
      104,  104,  104,  104,  104,   44,  104,  104,   46,  104,
      104,   42,   47,  104,  104,  104,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,  104,    0,  104,
      104,  104,  104,  104,  104,   61,  104,   63,   62,  104,
       64,  104,  104,  104,  104,  104,   43,  104,  104,  104,

      104,  104,  104,  104,  104,   45,  104,  104,  104,  104,
       36,  104,    0,  104,  104,  104,  104,   73,   71,   65,
       66,   74,   72,   54,   52,   50,  104,   34,   53,  104,
      104,   37,  104,  104,  104,  104,   51,  104,  104,    0,
       67,   69,   68,   70,  104,   38,  104,   56,   55,   40,
      104,   32,   39,    2,  104,   33,  104,  104,  104,  104,
      104,  104,  104,  104,  104,  104,  104,   35,  104,  104,
       41,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
       22,   23,   19,   19,   19,   19,   19,   24,   25,   26,
       27,   28,    1,   29,   19,   30,   31,   32,   33,   34,
       19,   19,   35,   19,   19,   36,   37,   19,   19,   38,
       19,   19,   39,   40,   19,   19,   41,   19,   19,   19,
       42,    1,   43,   44,   45,   46,   47,   48,   49,   50,

       51,   52,   53,   54,   55,   19,   56,   57,   58,   59,
       60,   61,   19,   62,   63,   64,   65,   66,   67,   68,
       69,   19,   70,   71,   72,   73,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[74] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    2,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    1,    1,    1,    2,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    1,
        1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[277] =
    {   0,
        0,    0,  292,  291,   71,   72,   73,   74,  293,  296,
      296,  296,  296,  296,  237,  296,  296,  296,  296,  296,
      296,  296,  296,  296,  296,  274,   68,    0,  296,  296,
      296,  296,  296,  296,  252,   48,   48,   51,  296,  296,
      296,  296,   30,   66,  242,  228,  225,  227,  238,   43,
       44,   49,  215,   48,   45,  296,  296,  296,  296,  296,
      296,  296,  296,  265,  296,  296,  296,  223,  264,  296,
      296,    0,   72,  249,  248,  247,  246,  245,  244,  219,
      209,   52,  223,  222,  208,  209,  205,  218,  204,   58,
      220,  211,    0,    0,    0,   65,  216,    0,   61,  201,

        0,    0,    0,    0,  211,  215,  296,  210,  103,   89,
       95,  213,  212,  218,  217,  209,  208,  202,  204,    0,
        0,  190,  193,  190,  182,  187,  189,  180,  178,  195,
      186,   74,  171,  175,  185,   86,  173,  185,  171,  179,
      176,    0,    0,    0,    0,  187,  186,  185,  184,  198,
      197,  100,  105,  196,  195,    0,  171,  173,    0,  175,
      160,    0,    0,  165,  169,  165,  158,  153,  150,  165,
      166,  161,  153,  150,  162,  158,  153,  147,  140,  174,
      173,  172,  171,  165,  164,    0,  157,    0,    0,  156,
        0,  161,  160,  143,  142,  128,    0,  144,  130,  138,

      125,  123,  128,  128,  131,    0,  136,  125,  113,  129,
        0,  116,  128,  142,  141,  140,  139,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  116,    0,    0,  113,
      120,    0,  119,  118,  107,  122,    0,  114,  106,  113,
        0,    0,    0,    0,  118,    0,  100,    0,    0,    0,
       95,    0,    0,  296,   99,    0,  112,   95,  100,  105,
       90,   89,  102,   95,   99,   82,   82,    0,   92,   74,
        0,  296,  146,  148,  150,  102
    } ;

static yyconst flex_int16_t yy_def[277] =
    {   0,
      272,    1,  273,  273,  274,  274,  275,  275,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  276,  272,  272,
      272,  272,  272,  272,  276,  276,  276,  276,  272,  272,
      272,  272,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,

      276,  276,  276,  276,  276,  276,  272,  272,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      272,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  272,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,

      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  272,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  272,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  272,  276,  276,  276,  276,  276,  276,
      276,  276,  276,  276,  276,  276,  276,  276,  276,  276,
      276,    0,  272,  272,  272,  272
    } ;

static yyconst flex_int16_t yy_nxt[370] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   28,
       28,   28,   28,   29,   30,   31,   32,   33,   34,   28,
       35,   28,   28,   28,   28,   36,   37,   28,   38,   28,
       28,   39,   40,   41,   28,   42,   28,   28,   43,   44,
       45,   46,   47,   28,   48,   28,   49,   28,   28,   28,
       50,   51,   52,   53,   54,   28,   55,   28,   28,   56,
       57,   58,   59,   63,   63,   66,   66,   67,   67,   74,
       70,   76,   78,   64,   64,   71,   82,   77,   75,   89,
       80,   79,   81,   91,   92,  101,   93,  102,   94,  105,

      120,  103,   95,   72,  109,   90,  106,  110,  129,  121,
      111,   96,   97,  133,  104,   98,   83,   99,  136,  137,
      146,  130,  142,  143,  144,  145,  148,  134,  168,  147,
      173,  186,  169,  174,  271,  149,  189,  187,  270,  269,
      188,  268,  190,  267,  266,  191,   60,   60,   62,   62,
       65,   65,  265,  264,  263,  262,  261,  260,  259,  258,
      257,  256,  255,  254,  253,  252,  251,  250,  249,  248,
      247,  246,  245,  244,  243,  242,  241,  240,  239,  238,
      237,  236,  235,  234,  233,  232,  231,  230,  229,  228,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,

      217,  216,  215,  214,  213,  212,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  185,  184,  183,  182,
      181,  180,  179,  178,  177,  176,  175,  172,  171,  170,
      167,  166,  165,  164,  163,  162,  161,  160,  159,  158,
      157,  156,  155,  154,  153,  152,  151,  150,  141,  140,
      139,  138,  135,  132,  131,  128,  127,  126,  125,  124,
      123,  122,  119,  118,  117,  116,  115,  114,  113,  112,
       69,  108,  107,  100,   88,   87,   86,   85,   84,   73,
       69,   68,  272,   61,   61,    9,  272,  272,  272,  272,

      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272
    } ;

static yyconst flex_int16_t yy_chk[370] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    6,    7,    8,    7,    8,   36,
       27,   37,   38,    5,    6,   27,   44,   37,   36,   50,
       43,   38,   43,   51,   51,   54,   52,   54,   52,   55,

       82,   54,   52,  276,   73,   50,   55,   73,   90,   82,
       73,   52,   52,   96,   54,   52,   44,   52,   99,   99,
      110,   90,  109,  109,  109,  109,  111,   96,  132,  110,
      136,  152,  132,  136,  270,  111,  153,  152,  269,  267,
      152,  266,  153,  265,  264,  153,  273,  273,  274,  274,
      275,  275,  263,  262,  261,  260,  259,  258,  257,  255,
      251,  247,  245,  240,  239,  238,  236,  235,  234,  233,
      231,  230,  227,  217,  216,  215,  214,  213,  212,  210,
      209,  208,  207,  205,  204,  203,  202,  201,  200,  199,
      198,  196,  195,  194,  193,  192,  190,  187,  185,  184,

      183,  182,  181,  180,  179,  178,  177,  176,  175,  174,
      173,  172,  171,  170,  169,  168,  167,  166,  165,  164,
      161,  160,  158,  157,  155,  154,  151,  150,  149,  148,
      147,  146,  141,  140,  139,  138,  137,  135,  134,  133,
      131,  130,  129,  128,  127,  126,  125,  124,  123,  122,
      119,  118,  117,  116,  115,  114,  113,  112,  108,  106,
      105,  100,   97,   92,   91,   89,   88,   87,   86,   85,
       84,   83,   81,   80,   79,   78,   77,   76,   75,   74,
       69,   68,   64,   53,   49,   48,   47,   46,   45,   35,
       26,   15,    9,    4,    3,  272,  272,  272,  272,  272,

      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272,  272,
      272,  272,  272,  272,  272,  272,  272,  272,  272
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int nds32_aie_scanner__flex_debug;
int nds32_aie_scanner__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *nds32_aie_scanner_text;
#line 1 "nds32-aie-scanner.l"
/*  
    Andes Coprocessor Extension Language Syntax for GNU Flex
*/
#line 5 "nds32-aie-scanner.l"
#include <stdlib.h>
#include <string.h>
#include <errno.h>

#include "nds32-aie-parser.h"

#include "nds32-aie-utils.h"

#define yylval          nds32_aie_lval

#define MAX_CODE_CONST  256
#define MAX_BLOCK_CONST  4096
#define MAX_INCLUDE_DEPTH 10

YY_BUFFER_STATE include_stack[MAX_INCLUDE_DEPTH];
int include_stack_ptr = 0;
void debug_scanner_state(int state);
#define DSPRINT_STATE(state) debug_scanner_state(state) 



#define YY_NO_INPUT 1
#line 678 "nds32-aie-scanner.c"

#define INITIAL 0
#define COMMENTA 1
#define COMMENTB 2
#define STRING 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int nds32_aie_scanner_lex_destroy (void );

int nds32_aie_scanner_get_debug (void );

void nds32_aie_scanner_set_debug (int debug_flag  );

YY_EXTRA_TYPE nds32_aie_scanner_get_extra (void );

void nds32_aie_scanner_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *nds32_aie_scanner_get_in (void );

void nds32_aie_scanner_set_in  (FILE * in_str  );

FILE *nds32_aie_scanner_get_out (void );

void nds32_aie_scanner_set_out  (FILE * out_str  );

int nds32_aie_scanner_get_leng (void );

char *nds32_aie_scanner_get_text (void );

int nds32_aie_scanner_get_lineno (void );

void nds32_aie_scanner_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int nds32_aie_scanner_wrap (void );
#else
extern int nds32_aie_scanner_wrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( nds32_aie_scanner_text, nds32_aie_scanner_leng, 1, nds32_aie_scanner_out )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( nds32_aie_scanner_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( nds32_aie_scanner_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, nds32_aie_scanner_in))==0 && ferror(nds32_aie_scanner_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(nds32_aie_scanner_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int nds32_aie_scanner_lex (void);

#define YY_DECL int nds32_aie_scanner_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after nds32_aie_scanner_text and nds32_aie_scanner_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 39 "nds32-aie-scanner.l"


 char string_buf[MAX_STR_CONST];
 char* string_buf_ptr = string_buf;
 int return_state = YY_START;
 
 /********************************************/
 /* Regular expressions for primitive tokens */
 /********************************************/

#line 877 "nds32-aie-scanner.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! nds32_aie_scanner_in )
			nds32_aie_scanner_in = stdin;

		if ( ! nds32_aie_scanner_out )
			nds32_aie_scanner_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			nds32_aie_scanner_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				nds32_aie_scanner__create_buffer(nds32_aie_scanner_in,YY_BUF_SIZE );
		}

		nds32_aie_scanner__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of nds32_aie_scanner_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 273 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 296 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 49 "nds32-aie-scanner.l"
{
    DSPRINT("Eating spaces: \"%s\"", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 54 "nds32-aie-scanner.l"
{
    DSPRINT("Including file: %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);
    //BEGIN(INCLUDE);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 60 "nds32-aie-scanner.l"
{
    DSPRINT("(PERCENT): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return PERCENT;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 69 "nds32-aie-scanner.l"
{
    DSPRINT("(COMMA): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return COMMA;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 78 "nds32-aie-scanner.l"
{
    DSPRINT("(SEMICOLON): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SEMICOLON;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 87 "nds32-aie-scanner.l"
{
    DSPRINT("(COLON): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return COLON;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 96 "nds32-aie-scanner.l"
{
    DSPRINT("(MINUS): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return MINUS;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 105 "nds32-aie-scanner.l"
{
    DSPRINT("(PLUS): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return PLUS;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 114 "nds32-aie-scanner.l"
{
    DSPRINT("(MUL): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return MUL;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 123 "nds32-aie-scanner.l"
{
    DSPRINT("(DIV): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return DIV;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 132 "nds32-aie-scanner.l"
{
    DSPRINT("(DOT): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return DOT;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 141 "nds32-aie-scanner.l"
{
    DSPRINT("(EQUAL): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return EQ;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 150 "nds32-aie-scanner.l"
{
    DSPRINT("(LT): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return LT;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 159 "nds32-aie-scanner.l"
{
    DSPRINT("(GT): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return GT;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 168 "nds32-aie-scanner.l"
{
    DSPRINT("(LPAREN): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return LPAREN;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 177 "nds32-aie-scanner.l"
{
    DSPRINT("(RPAREN): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return RPAREN;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 186 "nds32-aie-scanner.l"
{
    DSPRINT("(LBRACK): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return LBRACK;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 195 "nds32-aie-scanner.l"
{
    DSPRINT("(RBRACK): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return RBRACK;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 204 "nds32-aie-scanner.l"
{
    DSPRINT("(LBRACE): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return LBRACE;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 213 "nds32-aie-scanner.l"
{
    DSPRINT("(RBRACE): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return RBRACE;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 222 "nds32-aie-scanner.l"
{
    DSPRINT("(DOLLAR): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return DOLLAR;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 231 "nds32-aie-scanner.l"
{
    DSPRINT("(CROSS): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CROSS;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 240 "nds32-aie-scanner.l"
{
    DSPRINT("(PP): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return PP;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 249 "nds32-aie-scanner.l"
{
    DSPRINT("NOT: %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return NOT;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 258 "nds32-aie-scanner.l"
{
    DSPRINT("logic and: %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return LOGIC_AND;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 267 "nds32-aie-scanner.l"
{
    DSPRINT("logic or: %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return LOGIC_OR;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 276 "nds32-aie-scanner.l"
{
    DSPRINT("AT: %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return AT;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 285 "nds32-aie-scanner.l"
{
    DSPRINT("SQUARE: %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SQUARE;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 294 "nds32-aie-scanner.l"
{
    DSPRINT("SLASH: %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SLASH;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 303 "nds32-aie-scanner.l"
{
    DSPRINT("SDOT: %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SDOT;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 312 "nds32-aie-scanner.l"
{
    DSPRINT("RDOT: %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return RDOT;
}
	YY_BREAK
/********************************************/
/* Regular expressions for AIE symbol value */
/********************************************/
case 32:
YY_RULE_SETUP
#line 325 "nds32-aie-scanner.l"
{
    DSPRINT("(TYPEDEF): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return TYPEDEF;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 334 "nds32-aie-scanner.l"
{
    DSPRINT("(REGISTER): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return REGISTER;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 343 "nds32-aie-scanner.l"
{
    DSPRINT("(PSEUDO): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return PSEUDO;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 352 "nds32-aie-scanner.l"
{
    DSPRINT("(PARTIAL_PSEUDO): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return PARTIAL_PSEUDO;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 361 "nds32-aie-scanner.l"
{
    DSPRINT("(WIDTH): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return WIDTH;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 370 "nds32-aie-scanner.l"
{
    DSPRINT("(REGNUM): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return REGNUM;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 379 "nds32-aie-scanner.l"
{
   DSPRINT("(RD_INSN): %s", nds32_aie_scanner_text);
   DSPRINT_STATE(YY_START);

   yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
   if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
   return RD_INSN;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 388 "nds32-aie-scanner.l"
{
   DSPRINT("(WR_INSN): %s", nds32_aie_scanner_text);
   DSPRINT_STATE(YY_START);

   yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
   if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
   return WR_INSN;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 397 "nds32-aie-scanner.l"
{
    DSPRINT("(SYM_MAP): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SYM_MAP;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 406 "nds32-aie-scanner.l"
{
    DSPRINT("(AIE_SYMBOL_VALUE): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SYMBOL_VALUE_MAP;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 415 "nds32-aie-scanner.l"
{
    DSPRINT("(AIE_INSN): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return INSN;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 425 "nds32-aie-scanner.l"
{
    DSPRINT("(GROUP): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return GROUP;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 434 "nds32-aie-scanner.l"
{
    DSPRINT("(CPID): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CPID;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 443 "nds32-aie-scanner.l"
{
    DSPRINT("(STAGE): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return STAGE;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 452 "nds32-aie-scanner.l"
{
    DSPRINT("(EACK): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return EACK;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 461 "nds32-aie-scanner.l"
{
    DSPRINT("(LACK): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return LACK;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 470 "nds32-aie-scanner.l"
{
    DSPRINT("(D2C): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return D2C;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 479 "nds32-aie-scanner.l"
{
    DSPRINT("(D2M): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return D2M;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 488 "nds32-aie-scanner.l"
{
    DSPRINT("(FORMAT): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return FORMAT;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 497 "nds32-aie-scanner.l"
{
    DSPRINT("(SYNTAX): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SYNTAX;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 506 "nds32-aie-scanner.l"
{
    DSPRINT("(DECODE): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return DECODE;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 514 "nds32-aie-scanner.l"
{
    DSPRINT("(PSTAGE): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return PSTAGE;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 522 "nds32-aie-scanner.l"
{
    DSPRINT("(CSTAGE): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CSTAGE;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 530 "nds32-aie-scanner.l"
{
    DSPRINT("(SSSTAGE): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SSSTAGE;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 538 "nds32-aie-scanner.l"
{
    DSPRINT("(SSCYCLE): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SSCYCLE;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 547 "nds32-aie-scanner.l"
{
    DSPRINT("(CPE1): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CPE1;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 556 "nds32-aie-scanner.l"
{
    DSPRINT("(CPE2): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CPE2;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 565 "nds32-aie-scanner.l"
{
    DSPRINT("(CPE3): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CPE3;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 574 "nds32-aie-scanner.l"
{
    DSPRINT("(CPE4): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CPE4;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 583 "nds32-aie-scanner.l"
{
    DSPRINT("(MFCPD): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return MFCPD;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 592 "nds32-aie-scanner.l"
{
    DSPRINT("(MTCPD): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return MTCPD;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 601 "nds32-aie-scanner.l"
{
    DSPRINT("(MFCPW): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return MFCPW;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 610 "nds32-aie-scanner.l"
{
    DSPRINT("(MTCPW): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return MTCPW;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 619 "nds32-aie-scanner.l"
{
    DSPRINT("(MFCPPW): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return MFCPPW;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 628 "nds32-aie-scanner.l"
{
    DSPRINT("(MTCPPW): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return MTCPPW;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 637 "nds32-aie-scanner.l"
{
    DSPRINT("(CPLD_BI): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CPLD_BI;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 646 "nds32-aie-scanner.l"
{
    DSPRINT("(CPSD_BI): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CPSD_BI;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 655 "nds32-aie-scanner.l"
{
    DSPRINT("(CPLW_BI): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CPLW_BI;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 664 "nds32-aie-scanner.l"
{
    DSPRINT("(CPSW_BI): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CPSW_BI;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 673 "nds32-aie-scanner.l"
{
    DSPRINT("(LWC_BI): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return LWC_BI;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 682 "nds32-aie-scanner.l"
{
    DSPRINT("(SWC_BI): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SWC_BI;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 691 "nds32-aie-scanner.l"
{
    DSPRINT("(LDC_BI): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return LDC_BI;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 700 "nds32-aie-scanner.l"
{
    DSPRINT("(SDC_BI): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SDC_BI;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 709 "nds32-aie-scanner.l"
{
    DSPRINT("(CPLD): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CPLD;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 718 "nds32-aie-scanner.l"
{
    DSPRINT("(CPSD): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CPSD;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 727 "nds32-aie-scanner.l"
{
    DSPRINT("(CPLW): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CPLW;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 736 "nds32-aie-scanner.l"
{
    DSPRINT("(CPSW): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return CPSW;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 745 "nds32-aie-scanner.l"
{
    DSPRINT("(LWC): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return LWC;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 754 "nds32-aie-scanner.l"
{
    DSPRINT("(SWC): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SWC;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 763 "nds32-aie-scanner.l"
{
    DSPRINT("(LDC): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return LDC;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 772 "nds32-aie-scanner.l"
{
    DSPRINT("(SDC): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SDC;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 781 "nds32-aie-scanner.l"
{
    DSPRINT("(sd): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SD;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 790 "nds32-aie-scanner.l"
{
    DSPRINT("(sw): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SW;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 799 "nds32-aie-scanner.l"
{
    DSPRINT("(sh): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SH;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 808 "nds32-aie-scanner.l"
{
    DSPRINT("(sb): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SB;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 817 "nds32-aie-scanner.l"
{
    DSPRINT("(ud): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return UD;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 826 "nds32-aie-scanner.l"
{
    DSPRINT("(uw): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return UW;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 835 "nds32-aie-scanner.l"
{
    DSPRINT("(uh): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return UH;
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 844 "nds32-aie-scanner.l"
{
    DSPRINT("(ub): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return UB;
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 853 "nds32-aie-scanner.l"
{
    DSPRINT("(source operand): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SOURCE_OPERAND;
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 862 "nds32-aie-scanner.l"
{
    DSPRINT("(destination operand): %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return DESTINATION_OPERAND;
}
	YY_BREAK
/***********************************/
/* Regular expressions for Strings */
/***********************************/
case 93:
YY_RULE_SETUP
#line 875 "nds32-aie-scanner.l"
{
    string_buf[0] = '\0';
    string_buf_ptr = string_buf;
    return_state = YY_START;

    BEGIN(STRING);

    DSPRINT("%s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 886 "nds32-aie-scanner.l"
{
    BEGIN(return_state);
    
    DSPRINT("%s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(string_buf) + 1));
    strcpy(yylval.text, string_buf);
    return STR;
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 897 "nds32-aie-scanner.l"
{
    *string_buf_ptr++ = *nds32_aie_scanner_text;
    *string_buf_ptr = '\0';

    DSPRINT("(STR): %s", string_buf);
    DSPRINT_STATE(YY_START);
}
	YY_BREAK
case 96:
/* rule 96 can match eol */
YY_RULE_SETUP
#line 905 "nds32-aie-scanner.l"
{
    *string_buf_ptr = '\0';
    AIE_SPRINT(aie_error, "Unterminate string constant:%s", string_buf);
    yyterminate();
}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 911 "nds32-aie-scanner.l"
{
    *string_buf_ptr = '\0';
    AIE_SPRINT(aie_error, "Unexpected end of file");
    yyterminate();
}
	YY_BREAK
/********************************************/
/* Regular expressions for comment stytle A */
/********************************************/
case 97:
YY_RULE_SETUP
#line 921 "nds32-aie-scanner.l"
{
    DSPRINT("Entering comment");

    return_state = YY_START;
    BEGIN(COMMENTA);
}
	YY_BREAK
case 98:
/* rule 98 can match eol */
YY_RULE_SETUP
#line 928 "nds32-aie-scanner.l"
{
    INC_SLINE();
    BEGIN(return_state);

    DSPRINT("Leaving comment");
    DSPRINT_STATE(YY_START);
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 936 "nds32-aie-scanner.l"
{
    DSPRINT("%s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);
}
	YY_BREAK
case YY_STATE_EOF(COMMENTA):
#line 941 "nds32-aie-scanner.l"
{
    AIE_SPRINT(aie_error, "Unexpected end of file");
    yyterminate();
}
	YY_BREAK
/********************************************/
/* Regular expressions for comment stytle B */
/********************************************/
case 100:
YY_RULE_SETUP
#line 950 "nds32-aie-scanner.l"
{
    DSPRINT("Entering comment");
    return_state = YY_START;
    BEGIN(COMMENTB);
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 956 "nds32-aie-scanner.l"
{
    BEGIN(return_state);

    DSPRINT("Leaving comment");
    DSPRINT_STATE(YY_START);
}
	YY_BREAK
case 102:
/* rule 102 can match eol */
YY_RULE_SETUP
#line 963 "nds32-aie-scanner.l"
{
    INC_SLINE();
    DSPRINT("New line");
    DSPRINT_STATE(YY_START);
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 969 "nds32-aie-scanner.l"
{
    DSPRINT("%s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);
}
	YY_BREAK
case YY_STATE_EOF(COMMENTB):
#line 974 "nds32-aie-scanner.l"
{
    AIE_SPRINT(aie_error, "Unexpected end of file");
    yyterminate();
}
	YY_BREAK
/*---------------------------------*/
/* Regular expressions for numbers */
/*---------------------------------*/
case 104:
YY_RULE_SETUP
#line 983 "nds32-aie-scanner.l"
{
    unsigned long int tmp = 0;
    
    //priority of dec is higher than hex
    if (aie_strtoul(nds32_aie_scanner_text, 0, &tmp, 0)) {
        DSPRINT("(INT): %s = (%u)", nds32_aie_scanner_text, tmp);
        DSPRINT_STATE(YY_START);
        yylval.value = (unsigned int)tmp;
        return INT;
    }
    else if ('0' == nds32_aie_scanner_text[0] && ('x' == nds32_aie_scanner_text[1] || 'X' == nds32_aie_scanner_text[1]) && (aie_strtoul(nds32_aie_scanner_text, 16, &tmp, 0))) {
        DSPRINT("(INT): %s = (%u)", nds32_aie_scanner_text, tmp);
        DSPRINT_STATE(YY_START);
        yylval.value = (unsigned int)tmp;
        return INT;
    }
    else if ('0' == nds32_aie_scanner_text[0] || '1' == nds32_aie_scanner_text[0] || '2' == nds32_aie_scanner_text[0] || '3' == nds32_aie_scanner_text[0] || '4' == nds32_aie_scanner_text[0] || '5' == nds32_aie_scanner_text[0] || '6' == nds32_aie_scanner_text[0] || '7' == nds32_aie_scanner_text[0] || '8' == nds32_aie_scanner_text[0] || '9' == nds32_aie_scanner_text[0]) {
        AIE_SPRINT(aie_error, "Can't not conver `%s' to 'unsigned long int', possible it is not a representable value", nds32_aie_scanner_text);
        yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
        if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_IMPRESENTABLE_TOKEN;};
        return INVALID_PRESENTABLE_TOKEN;
    }
    else {
        DSPRINT("(ID): %s", nds32_aie_scanner_text);
        DSPRINT_STATE(YY_START);

        yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
        if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_IMPRESENTABLE_TOKEN;};
        return ID;

    }
}
	YY_BREAK
case 105:
/* rule 105 can match eol */
YY_RULE_SETUP
#line 1016 "nds32-aie-scanner.l"
{
    DSPRINT("New line");
    DSPRINT_STATE(YY_START); 
    INC_SLINE();
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 1022 "nds32-aie-scanner.l"
{
    DSPRINT("Skip: %s", nds32_aie_scanner_text);
    DSPRINT_STATE(YY_START);

    yylval.text = (char*) malloc(sizeof(char) * (strlen(nds32_aie_scanner_text) + 1));
    if(!aie_strcpy(yylval.text, nds32_aie_scanner_text)) { return INVALID_PRESENTABLE_TOKEN;};
    return SKIP;
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 1031 "nds32-aie-scanner.l"
ECHO;
	YY_BREAK
#line 2273 "nds32-aie-scanner.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed nds32_aie_scanner_in at a new source and called
			 * nds32_aie_scanner_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = nds32_aie_scanner_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( nds32_aie_scanner_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * nds32_aie_scanner_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of nds32_aie_scanner_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					nds32_aie_scanner_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			nds32_aie_scanner_restart(nds32_aie_scanner_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) nds32_aie_scanner_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 273 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 273 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 272);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					nds32_aie_scanner_restart(nds32_aie_scanner_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( nds32_aie_scanner_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve nds32_aie_scanner_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void nds32_aie_scanner_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        nds32_aie_scanner_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            nds32_aie_scanner__create_buffer(nds32_aie_scanner_in,YY_BUF_SIZE );
	}

	nds32_aie_scanner__init_buffer(YY_CURRENT_BUFFER,input_file );
	nds32_aie_scanner__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void nds32_aie_scanner__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		nds32_aie_scanner_pop_buffer_state();
	 *		nds32_aie_scanner_push_buffer_state(new_buffer);
     */
	nds32_aie_scanner_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	nds32_aie_scanner__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (nds32_aie_scanner_wrap()) processing, but the only time this flag
	 * is looked at is after nds32_aie_scanner_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void nds32_aie_scanner__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	nds32_aie_scanner_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE nds32_aie_scanner__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) nds32_aie_scanner_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in nds32_aie_scanner__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) nds32_aie_scanner_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in nds32_aie_scanner__create_buffer()" );

	b->yy_is_our_buffer = 1;

	nds32_aie_scanner__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with nds32_aie_scanner__create_buffer()
 * 
 */
    void nds32_aie_scanner__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		nds32_aie_scanner_free((void *) b->yy_ch_buf  );

	nds32_aie_scanner_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a nds32_aie_scanner_restart() or at EOF.
 */
    static void nds32_aie_scanner__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	nds32_aie_scanner__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then nds32_aie_scanner__init_buffer was _probably_
     * called from nds32_aie_scanner_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void nds32_aie_scanner__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		nds32_aie_scanner__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void nds32_aie_scanner_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	nds32_aie_scanner_ensure_buffer_stack();

	/* This block is copied from nds32_aie_scanner__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from nds32_aie_scanner__switch_to_buffer. */
	nds32_aie_scanner__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void nds32_aie_scanner_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	nds32_aie_scanner__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		nds32_aie_scanner__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void nds32_aie_scanner_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)nds32_aie_scanner_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in nds32_aie_scanner_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)nds32_aie_scanner_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in nds32_aie_scanner_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE nds32_aie_scanner__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) nds32_aie_scanner_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in nds32_aie_scanner__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	nds32_aie_scanner__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to nds32_aie_scanner_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       nds32_aie_scanner__scan_bytes() instead.
 */
YY_BUFFER_STATE nds32_aie_scanner__scan_string (yyconst char * yystr )
{
    
	return nds32_aie_scanner__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to nds32_aie_scanner_lex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE nds32_aie_scanner__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) nds32_aie_scanner_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in nds32_aie_scanner__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = nds32_aie_scanner__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in nds32_aie_scanner__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up nds32_aie_scanner_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		nds32_aie_scanner_text[nds32_aie_scanner_leng] = (yy_hold_char); \
		(yy_c_buf_p) = nds32_aie_scanner_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		nds32_aie_scanner_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int nds32_aie_scanner_get_lineno  (void)
{
        
    return nds32_aie_scanner_lineno;
}

/** Get the input stream.
 * 
 */
FILE *nds32_aie_scanner_get_in  (void)
{
        return nds32_aie_scanner_in;
}

/** Get the output stream.
 * 
 */
FILE *nds32_aie_scanner_get_out  (void)
{
        return nds32_aie_scanner_out;
}

/** Get the length of the current token.
 * 
 */
int nds32_aie_scanner_get_leng  (void)
{
        return nds32_aie_scanner_leng;
}

/** Get the current token.
 * 
 */

char *nds32_aie_scanner_get_text  (void)
{
        return nds32_aie_scanner_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void nds32_aie_scanner_set_lineno (int  line_number )
{
    
    nds32_aie_scanner_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see nds32_aie_scanner__switch_to_buffer
 */
void nds32_aie_scanner_set_in (FILE *  in_str )
{
        nds32_aie_scanner_in = in_str ;
}

void nds32_aie_scanner_set_out (FILE *  out_str )
{
        nds32_aie_scanner_out = out_str ;
}

int nds32_aie_scanner_get_debug  (void)
{
        return nds32_aie_scanner__flex_debug;
}

void nds32_aie_scanner_set_debug (int  bdebug )
{
        nds32_aie_scanner__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from nds32_aie_scanner_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    nds32_aie_scanner_in = stdin;
    nds32_aie_scanner_out = stdout;
#else
    nds32_aie_scanner_in = (FILE *) 0;
    nds32_aie_scanner_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * nds32_aie_scanner_lex_init()
     */
    return 0;
}

/* nds32_aie_scanner_lex_destroy is for both reentrant and non-reentrant scanners. */
int nds32_aie_scanner_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		nds32_aie_scanner__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		nds32_aie_scanner_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	nds32_aie_scanner_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * nds32_aie_scanner_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *nds32_aie_scanner_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *nds32_aie_scanner_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void nds32_aie_scanner_free (void * ptr )
{
	free( (char *) ptr );	/* see nds32_aie_scanner_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 1031 "nds32-aie-scanner.l"



void debug_scanner_state(int state) {
    switch (state) {
        case COMMENTA:
            DSPRINT("SState: COMMENTA");
            break;
        case COMMENTB:
            DSPRINT("SState: COMMENTB");
            break;
        case STRING:
            DSPRINT("SState: STRING");
            break;
        case INITIAL:
            DSPRINT("SState: INITIAL");
            break;
        default:
            DSPRINT("SState: Uknown");
            break;
    }
}

